/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'koding-api/InlineResponse200Data'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse200Data'));
  } else {
    // Browser globals (root is window)
    if (!root.KodingApi) {
      root.KodingApi = {};
    }
    root.KodingApi.InlineResponse200 = factory(root.KodingApi.ApiClient, root.KodingApi.InlineResponse200Data);
  }
}(this, function(ApiClient, InlineResponse200Data) {
  'use strict';




  /**
   * The InlineResponse200 model module.
   * @module koding-api/InlineResponse200
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>InlineResponse200</code>.
   * @alias module:koding-api/InlineResponse200
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:koding-api/InlineResponse200} obj Optional instance to populate.
   * @return {module:koding-api/InlineResponse200} The populated <code>InlineResponse200</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ok')) {
        obj['ok'] = ApiClient.convertToType(data['ok'], 'Boolean');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], Object);
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = InlineResponse200Data.constructFromObject(data['data']);
      }
    }
    return obj;
  }

  /**
   * If the request processed by endpoint
   * @member {Boolean} ok
   */
  exports.prototype['ok'] = undefined;
  /**
   * Error description
   * @member {Object} error
   */
  exports.prototype['error'] = undefined;
  /**
   * @member {module:koding-api/InlineResponse200Data} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


