/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'koding-api/JMachineStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./JMachineStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.KodingApi) {
      root.KodingApi = {};
    }
    root.KodingApi.JComputeStack = factory(root.KodingApi.ApiClient, root.KodingApi.JMachineStatus);
  }
}(this, function(ApiClient, JMachineStatus) {
  'use strict';




  /**
   * The JComputeStack model module.
   * @module koding-api/JComputeStack
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>JComputeStack</code>.
   * @alias module:koding-api/JComputeStack
   * @class
   * @param title {String} 
   * @param originId {String} 
   * @param group {String} 
   */
  var exports = function(title, originId, group) {
    var _this = this;


    _this['title'] = title;
    _this['originId'] = originId;
    _this['group'] = group;







  };

  /**
   * Constructs a <code>JComputeStack</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:koding-api/JComputeStack} obj Optional instance to populate.
   * @return {module:koding-api/JComputeStack} The populated <code>JComputeStack</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('originId')) {
        obj['originId'] = ApiClient.convertToType(data['originId'], 'String');
      }
      if (data.hasOwnProperty('group')) {
        obj['group'] = ApiClient.convertToType(data['group'], 'String');
      }
      if (data.hasOwnProperty('baseStackId')) {
        obj['baseStackId'] = ApiClient.convertToType(data['baseStackId'], 'String');
      }
      if (data.hasOwnProperty('stackRevision')) {
        obj['stackRevision'] = ApiClient.convertToType(data['stackRevision'], 'String');
      }
      if (data.hasOwnProperty('machines')) {
        obj['machines'] = ApiClient.convertToType(data['machines'], Object);
      }
      if (data.hasOwnProperty('config')) {
        obj['config'] = ApiClient.convertToType(data['config'], Object);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = ApiClient.convertToType(data['meta'], Object);
      }
      if (data.hasOwnProperty('credentials')) {
        obj['credentials'] = ApiClient.convertToType(data['credentials'], Object);
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = JMachineStatus.constructFromObject(data['status']);
      }
    }
    return obj;
  }

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} originId
   */
  exports.prototype['originId'] = undefined;
  /**
   * @member {String} group
   */
  exports.prototype['group'] = undefined;
  /**
   * @member {String} baseStackId
   */
  exports.prototype['baseStackId'] = undefined;
  /**
   * @member {String} stackRevision
   */
  exports.prototype['stackRevision'] = undefined;
  /**
   * @member {Object} machines
   */
  exports.prototype['machines'] = undefined;
  /**
   * @member {Object} config
   */
  exports.prototype['config'] = undefined;
  /**
   * @member {Object} meta
   */
  exports.prototype['meta'] = undefined;
  /**
   * @member {Object} credentials
   */
  exports.prototype['credentials'] = undefined;
  /**
   * @member {module:koding-api/JMachineStatus} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


