/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KodingApi) {
      root.KodingApi = {};
    }
    root.KodingApi.JForeignAuth = factory(root.KodingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The JForeignAuth model module.
   * @module koding-api/JForeignAuth
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>JForeignAuth</code>.
   * @alias module:koding-api/JForeignAuth
   * @class
   * @param username {String} 
   * @param group {String} 
   * @param provider {String} 
   * @param foreignId {String} 
   */
  var exports = function(username, group, provider, foreignId) {
    var _this = this;


    _this['username'] = username;
    _this['group'] = group;
    _this['provider'] = provider;
    _this['foreignId'] = foreignId;

  };

  /**
   * Constructs a <code>JForeignAuth</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:koding-api/JForeignAuth} obj Optional instance to populate.
   * @return {module:koding-api/JForeignAuth} The populated <code>JForeignAuth</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('group')) {
        obj['group'] = ApiClient.convertToType(data['group'], 'String');
      }
      if (data.hasOwnProperty('provider')) {
        obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
      }
      if (data.hasOwnProperty('foreignId')) {
        obj['foreignId'] = ApiClient.convertToType(data['foreignId'], 'String');
      }
      if (data.hasOwnProperty('foreignData')) {
        obj['foreignData'] = ApiClient.convertToType(data['foreignData'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * @member {String} group
   */
  exports.prototype['group'] = undefined;
  /**
   * @member {String} provider
   */
  exports.prototype['provider'] = undefined;
  /**
   * @member {String} foreignId
   */
  exports.prototype['foreignId'] = undefined;
  /**
   * @member {Object} foreignData
   */
  exports.prototype['foreignData'] = undefined;



  return exports;
}));


