/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KodingApi) {
      root.KodingApi = {};
    }
    root.KodingApi.JGroupLimitRestrictions = factory(root.KodingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The JGroupLimitRestrictions model module.
   * @module koding-api/JGroupLimitRestrictions
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>JGroupLimitRestrictions</code>.
   * @alias module:koding-api/JGroupLimitRestrictions
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>JGroupLimitRestrictions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:koding-api/JGroupLimitRestrictions} obj Optional instance to populate.
   * @return {module:koding-api/JGroupLimitRestrictions} The populated <code>JGroupLimitRestrictions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('supports')) {
        obj['supports'] = ApiClient.convertToType(data['supports'], ['String']);
      }
      if (data.hasOwnProperty('provider')) {
        obj['provider'] = ApiClient.convertToType(data['provider'], ['String']);
      }
      if (data.hasOwnProperty('resource')) {
        obj['resource'] = ApiClient.convertToType(data['resource'], ['String']);
      }
      if (data.hasOwnProperty('custom')) {
        obj['custom'] = ApiClient.convertToType(data['custom'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} supports
   */
  exports.prototype['supports'] = undefined;
  /**
   * @member {Array.<String>} provider
   */
  exports.prototype['provider'] = undefined;
  /**
   * @member {Array.<String>} resource
   */
  exports.prototype['resource'] = undefined;
  /**
   * @member {Object} custom
   */
  exports.prototype['custom'] = undefined;



  return exports;
}));


