/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KodingApi) {
      root.KodingApi = {};
    }
    root.KodingApi.JProposedDomainProxy = factory(root.KodingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The JProposedDomainProxy model module.
   * @module koding-api/JProposedDomainProxy
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>JProposedDomainProxy</code>.
   * @alias module:koding-api/JProposedDomainProxy
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>JProposedDomainProxy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:koding-api/JProposedDomainProxy} obj Optional instance to populate.
   * @return {module:koding-api/JProposedDomainProxy} The populated <code>JProposedDomainProxy</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mode')) {
        obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
      }
      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('serviceName')) {
        obj['serviceName'] = ApiClient.convertToType(data['serviceName'], 'String');
      }
      if (data.hasOwnProperty('key')) {
        obj['key'] = ApiClient.convertToType(data['key'], 'String');
      }
      if (data.hasOwnProperty('fullUrl')) {
        obj['fullUrl'] = ApiClient.convertToType(data['fullUrl'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} mode
   */
  exports.prototype['mode'] = undefined;
  /**
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * @member {String} serviceName
   */
  exports.prototype['serviceName'] = undefined;
  /**
   * @member {String} key
   */
  exports.prototype['key'] = undefined;
  /**
   * @member {String} fullUrl
   */
  exports.prototype['fullUrl'] = undefined;



  return exports;
}));


