/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'koding-api/JSessionForeignAuth'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./JSessionForeignAuth'));
  } else {
    // Browser globals (root is window)
    if (!root.KodingApi) {
      root.KodingApi = {};
    }
    root.KodingApi.JSession = factory(root.KodingApi.ApiClient, root.KodingApi.JSessionForeignAuth);
  }
}(this, function(ApiClient, JSessionForeignAuth) {
  'use strict';




  /**
   * The JSession model module.
   * @module koding-api/JSession
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>JSession</code>.
   * @alias module:koding-api/JSession
   * @class
   */
  var exports = function() {
    var _this = this;

















  };

  /**
   * Constructs a <code>JSession</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:koding-api/JSession} obj Optional instance to populate.
   * @return {module:koding-api/JSession} The populated <code>JSession</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('clientId')) {
        obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
      }
      if (data.hasOwnProperty('clientIP')) {
        obj['clientIP'] = ApiClient.convertToType(data['clientIP'], 'String');
      }
      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('otaToken')) {
        obj['otaToken'] = ApiClient.convertToType(data['otaToken'], 'String');
      }
      if (data.hasOwnProperty('groupName')) {
        obj['groupName'] = ApiClient.convertToType(data['groupName'], 'String');
      }
      if (data.hasOwnProperty('guestId')) {
        obj['guestId'] = ApiClient.convertToType(data['guestId'], 'Number');
      }
      if (data.hasOwnProperty('terminalId')) {
        obj['terminalId'] = ApiClient.convertToType(data['terminalId'], 'String');
      }
      if (data.hasOwnProperty('sessionBegan')) {
        obj['sessionBegan'] = ApiClient.convertToType(data['sessionBegan'], 'Date');
      }
      if (data.hasOwnProperty('guestSessionBegan')) {
        obj['guestSessionBegan'] = ApiClient.convertToType(data['guestSessionBegan'], 'Date');
      }
      if (data.hasOwnProperty('lastAccess')) {
        obj['lastAccess'] = ApiClient.convertToType(data['lastAccess'], 'Date');
      }
      if (data.hasOwnProperty('foreignAuth')) {
        obj['foreignAuth'] = JSessionForeignAuth.constructFromObject(data['foreignAuth']);
      }
      if (data.hasOwnProperty('returnUrl')) {
        obj['returnUrl'] = ApiClient.convertToType(data['returnUrl'], 'String');
      }
      if (data.hasOwnProperty('foreignAuthType')) {
        obj['foreignAuthType'] = ApiClient.convertToType(data['foreignAuthType'], 'String');
      }
      if (data.hasOwnProperty('impersonating')) {
        obj['impersonating'] = ApiClient.convertToType(data['impersonating'], 'Boolean');
      }
      if (data.hasOwnProperty('sessionData')) {
        obj['sessionData'] = ApiClient.convertToType(data['sessionData'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} clientId
   */
  exports.prototype['clientId'] = undefined;
  /**
   * @member {String} clientIP
   */
  exports.prototype['clientIP'] = undefined;
  /**
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * @member {String} otaToken
   */
  exports.prototype['otaToken'] = undefined;
  /**
   * @member {String} groupName
   */
  exports.prototype['groupName'] = undefined;
  /**
   * @member {Number} guestId
   */
  exports.prototype['guestId'] = undefined;
  /**
   * @member {String} terminalId
   */
  exports.prototype['terminalId'] = undefined;
  /**
   * @member {Date} sessionBegan
   */
  exports.prototype['sessionBegan'] = undefined;
  /**
   * @member {Date} guestSessionBegan
   */
  exports.prototype['guestSessionBegan'] = undefined;
  /**
   * @member {Date} lastAccess
   */
  exports.prototype['lastAccess'] = undefined;
  /**
   * @member {module:koding-api/JSessionForeignAuth} foreignAuth
   */
  exports.prototype['foreignAuth'] = undefined;
  /**
   * @member {String} returnUrl
   */
  exports.prototype['returnUrl'] = undefined;
  /**
   * @member {String} foreignAuthType
   */
  exports.prototype['foreignAuthType'] = undefined;
  /**
   * @member {Boolean} impersonating
   */
  exports.prototype['impersonating'] = undefined;
  /**
   * @member {Object} sessionData
   */
  exports.prototype['sessionData'] = undefined;



  return exports;
}));


