/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'koding-api/JStackTemplateTemplate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./JStackTemplateTemplate'));
  } else {
    // Browser globals (root is window)
    if (!root.KodingApi) {
      root.KodingApi = {};
    }
    root.KodingApi.JStackTemplate = factory(root.KodingApi.ApiClient, root.KodingApi.JStackTemplateTemplate);
  }
}(this, function(ApiClient, JStackTemplateTemplate) {
  'use strict';




  /**
   * The JStackTemplate model module.
   * @module koding-api/JStackTemplate
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>JStackTemplate</code>.
   * @alias module:koding-api/JStackTemplate
   * @class
   * @param title {String} Title of this stack template
   * @param slug {String} Unique slug of stack template
   * @param originId {String} 
   * @param group {String} 
   */
  var exports = function(title, slug, originId, group) {
    var _this = this;



    _this['title'] = title;
    _this['slug'] = slug;



    _this['originId'] = originId;

    _this['group'] = group;


  };

  /**
   * Constructs a <code>JStackTemplate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:koding-api/JStackTemplate} obj Optional instance to populate.
   * @return {module:koding-api/JStackTemplate} The populated <code>JStackTemplate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('machines')) {
        obj['machines'] = ApiClient.convertToType(data['machines'], [Object]);
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('slug')) {
        obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('config')) {
        obj['config'] = ApiClient.convertToType(data['config'], Object);
      }
      if (data.hasOwnProperty('accessLevel')) {
        obj['accessLevel'] = ApiClient.convertToType(data['accessLevel'], 'String');
      }
      if (data.hasOwnProperty('originId')) {
        obj['originId'] = ApiClient.convertToType(data['originId'], 'String');
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = ApiClient.convertToType(data['meta'], Object);
      }
      if (data.hasOwnProperty('group')) {
        obj['group'] = ApiClient.convertToType(data['group'], 'String');
      }
      if (data.hasOwnProperty('template')) {
        obj['template'] = JStackTemplateTemplate.constructFromObject(data['template']);
      }
      if (data.hasOwnProperty('credentials')) {
        obj['credentials'] = ApiClient.convertToType(data['credentials'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {Array.<Object>} machines
   */
  exports.prototype['machines'] = undefined;
  /**
   * Title of this stack template
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Unique slug of stack template
   * @member {String} slug
   */
  exports.prototype['slug'] = undefined;
  /**
   * Stack template description
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * Private config data for stack template
   * @member {Object} config
   */
  exports.prototype['config'] = undefined;
  /**
   * @member {String} accessLevel
   */
  exports.prototype['accessLevel'] = undefined;
  /**
   * @member {String} originId
   */
  exports.prototype['originId'] = undefined;
  /**
   * @member {Object} meta
   */
  exports.prototype['meta'] = undefined;
  /**
   * @member {String} group
   */
  exports.prototype['group'] = undefined;
  /**
   * @member {module:koding-api/JStackTemplateTemplate} template
   */
  exports.prototype['template'] = undefined;
  /**
   * @member {Object} credentials
   */
  exports.prototype['credentials'] = undefined;



  return exports;
}));


