/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KodingApi);
  }
}(this, function(expect, KodingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KodingApi.JAccount();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JAccount', function() {
    it('should create an instance of JAccount', function() {
      // uncomment below and update the code to test JAccount
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be.a(KodingApi.JAccount);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property socialApiId (base name: "socialApiId")', function() {
      // uncomment below and update the code to test the property socialApiId
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property environmentIsCreated (base name: "environmentIsCreated")', function() {
      // uncomment below and update the code to test the property environmentIsCreated
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property profile (base name: "profile")', function() {
      // uncomment below and update the code to test the property profile
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property referrerUsername (base name: "referrerUsername")', function() {
      // uncomment below and update the code to test the property referrerUsername
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property referralUsed (base name: "referralUsed")', function() {
      // uncomment below and update the code to test the property referralUsed
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property isExempt (base name: "isExempt")', function() {
      // uncomment below and update the code to test the property isExempt
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property globalFlags (base name: "globalFlags")', function() {
      // uncomment below and update the code to test the property globalFlags
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

    it('should have the property meta (base name: "meta")', function() {
      // uncomment below and update the code to test the property meta
      //var instane = new KodingApi.JAccount();
      //expect(instance).to.be();
    });

  });

}));
