/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KodingApi);
  }
}(this, function(expect, KodingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KodingApi.JCustomPartials();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JCustomPartials', function() {
    it('should create an instance of JCustomPartials', function() {
      // uncomment below and update the code to test JCustomPartials
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be.a(KodingApi.JCustomPartials);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property partialType (base name: "partialType")', function() {
      // uncomment below and update the code to test the property partialType
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property partial (base name: "partial")', function() {
      // uncomment below and update the code to test the property partial
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "isActive")', function() {
      // uncomment below and update the code to test the property isActive
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property isPreview (base name: "isPreview")', function() {
      // uncomment below and update the code to test the property isPreview
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property previewInstance (base name: "previewInstance")', function() {
      // uncomment below and update the code to test the property previewInstance
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property viewInstance (base name: "viewInstance")', function() {
      // uncomment below and update the code to test the property viewInstance
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

    it('should have the property publishedAt (base name: "publishedAt")', function() {
      // uncomment below and update the code to test the property publishedAt
      //var instane = new KodingApi.JCustomPartials();
      //expect(instance).to.be();
    });

  });

}));
