/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KodingApi);
  }
}(this, function(expect, KodingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KodingApi.JGroupCustomize();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JGroupCustomize', function() {
    it('should create an instance of JGroupCustomize', function() {
      // uncomment below and update the code to test JGroupCustomize
      //var instane = new KodingApi.JGroupCustomize();
      //expect(instance).to.be.a(KodingApi.JGroupCustomize);
    });

    it('should have the property coverPhoto (base name: "coverPhoto")', function() {
      // uncomment below and update the code to test the property coverPhoto
      //var instane = new KodingApi.JGroupCustomize();
      //expect(instance).to.be();
    });

    it('should have the property logo (base name: "logo")', function() {
      // uncomment below and update the code to test the property logo
      //var instane = new KodingApi.JGroupCustomize();
      //expect(instance).to.be();
    });

    it('should have the property chatlioId (base name: "chatlioId")', function() {
      // uncomment below and update the code to test the property chatlioId
      //var instane = new KodingApi.JGroupCustomize();
      //expect(instance).to.be();
    });

  });

}));
