/**
 * Koding API
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KodingApi);
  }
}(this, function(expect, KodingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KodingApi.JPasswordRecovery();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JPasswordRecovery', function() {
    it('should create an instance of JPasswordRecovery', function() {
      // uncomment below and update the code to test JPasswordRecovery
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be.a(KodingApi.JPasswordRecovery);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

    it('should have the property redeemedAt (base name: "redeemedAt")', function() {
      // uncomment below and update the code to test the property redeemedAt
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

    it('should have the property expiresAt (base name: "expiresAt")', function() {
      // uncomment below and update the code to test the property expiresAt
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

    it('should have the property expires (base name: "expires")', function() {
      // uncomment below and update the code to test the property expires
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

    it('should have the property requestedAt (base name: "requestedAt")', function() {
      // uncomment below and update the code to test the property requestedAt
      //var instane = new KodingApi.JPasswordRecovery();
      //expect(instance).to.be();
    });

  });

}));
